self-hosted-runner:
  labels:
    - cranesystemtest
config-variables:
  - CRANESCHED_PRIVILEGED_RUNNER_GROUP
  - CRANETESTKIT_RELEASE_DIR
  - CRANETESTKIT_AUTOTEST_SHA
  - CRANETESTKIT_EXECUTABLE_SHA256
  - CRANETESTKIT_PROFILE_PATH
  - CRANETESTKIT_PROFILE_SHA256
  - CRANETESTKIT_BUNDLE_ID
  - CRANETESTKIT_IMAGE_RUNTIME_SHA256
  - CRANETESTKIT_K3S_EXECUTABLE
  - CRANETESTKIT_KUBECONFIG
  - CRANETESTKIT_NFS_ROOT
  - CRANETESTKIT_CCACHE_DIR
  - CRANETESTKIT_FETCHCONTENT_DIR
