# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  poem: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true