# EmbeddedDb settings
# BerkeleyDB or Unqlite(default)
CraneEmbeddedDbBackend: Unqlite
# File path of CraneCtld embeded DB (Relative to CraneBaseDir, when set Keepalived, Relative to CraneSharedBaseDir)
CraneCtldDbPath: cranectld/embedded.db

# Mongodb settings
DbUser: admin
DbPassword: "123456"
DbHost: localhost
DbPort: 27017
DbReplSetName: crane_rs
DbName: crane_db
# Job aggregation timeout in milliseconds for MongoDB operations.
JobAggregationTimeoutMs: 600000
# Job aggregation batch size for MongoDB operations.
JobAggregationBatchSize: 100

Vault:
  Enabled: false
  Addr: 127.0.0.1
  Port: 8200
  Username: admin
  Password: "123456"
  Tls: false
  ExpirationMinutes: 30
