# EmbeddedDb settings
CraneEmbeddedDbBackend: Unqlite  # BerkeleyDB or Unqlite(default)
CraneCtldDbPath: /tmp/cranectld/embedded.db

# Mongodb settings
DbUser: admin
DbPassword: "123456"
DbHost: localhost
DbPort: 27017
DbReplSetName: crane_rs
DbName: crane_db