// Generated by scripts/generate_execution_flow_schema.py. DO NOT EDIT.
// Source: schemas/execution-flow/v1.yaml
// SHA256: 850ffaaf06e57ab7eabc34a2fb17cde92c172d45de7ef886fa05333f929f71c9
#pragma once

#include <cstdint>
#include <string_view>

namespace crane {

// clang-format off

inline constexpr std::string_view kExecutionFlowSchemaSha256 = "850ffaaf06e57ab7eabc34a2fb17cde92c172d45de7ef886fa05333f929f71c9";
inline constexpr std::string_view kExecutionFlowSchemaName = "flow/v1";
inline constexpr std::string_view kExecutionFlowSchemaVersion = "v1";
inline constexpr std::string_view kExecutionFlowWirePrefix = "flow/v1/";
inline constexpr std::string_view kExecutionFlowHeartbeatPoint = "flow/v1/pipeline/heartbeat";
inline constexpr std::string_view kExecutionFlowPipelineFaultPoint = "flow/v1/pipeline/fault";

enum class FlowWireType {
  kInt64,
  kString,
  kEnum,
};

enum class FlowEnvelopeRequirement {
  kAlways,
  kBusiness,
  kOptional,
};

enum class FlowEnvelopeAttribute {
  kEventSequence,
  kFlowId,
  kFlowSchema,
  kPoint,
  kProducer,
  kServiceInstance,
  kServiceLogicalInstance,
  kCount,
};

[[nodiscard]] constexpr std::string_view FlowEnvelopeAttributeName(
    FlowEnvelopeAttribute attribute) {
  switch (attribute) {
    case FlowEnvelopeAttribute::kEventSequence: return "event_sequence";
    case FlowEnvelopeAttribute::kFlowId: return "flow_id";
    case FlowEnvelopeAttribute::kFlowSchema: return "flow_schema";
    case FlowEnvelopeAttribute::kPoint: return "point";
    case FlowEnvelopeAttribute::kProducer: return "producer";
    case FlowEnvelopeAttribute::kServiceInstance: return "service_instance";
    case FlowEnvelopeAttribute::kServiceLogicalInstance: return "service_logical_instance";
    case FlowEnvelopeAttribute::kCount: break;
  }
  return {};
}

[[nodiscard]] constexpr FlowWireType FlowEnvelopeAttributeWireType(
    FlowEnvelopeAttribute attribute) {
  switch (attribute) {
    case FlowEnvelopeAttribute::kEventSequence: return FlowWireType::kInt64;
    case FlowEnvelopeAttribute::kFlowId: return FlowWireType::kString;
    case FlowEnvelopeAttribute::kFlowSchema: return FlowWireType::kString;
    case FlowEnvelopeAttribute::kPoint: return FlowWireType::kString;
    case FlowEnvelopeAttribute::kProducer: return FlowWireType::kString;
    case FlowEnvelopeAttribute::kServiceInstance: return FlowWireType::kString;
    case FlowEnvelopeAttribute::kServiceLogicalInstance: return FlowWireType::kString;
    case FlowEnvelopeAttribute::kCount: break;
  }
  return FlowWireType::kString;
}

[[nodiscard]] constexpr FlowEnvelopeRequirement
FlowEnvelopeAttributeRequirement(FlowEnvelopeAttribute attribute) {
  switch (attribute) {
    case FlowEnvelopeAttribute::kEventSequence: return FlowEnvelopeRequirement::kAlways;
    case FlowEnvelopeAttribute::kFlowId: return FlowEnvelopeRequirement::kBusiness;
    case FlowEnvelopeAttribute::kFlowSchema: return FlowEnvelopeRequirement::kAlways;
    case FlowEnvelopeAttribute::kPoint: return FlowEnvelopeRequirement::kAlways;
    case FlowEnvelopeAttribute::kProducer: return FlowEnvelopeRequirement::kAlways;
    case FlowEnvelopeAttribute::kServiceInstance: return FlowEnvelopeRequirement::kAlways;
    case FlowEnvelopeAttribute::kServiceLogicalInstance: return FlowEnvelopeRequirement::kAlways;
    case FlowEnvelopeAttribute::kCount: break;
  }
  return FlowEnvelopeRequirement::kOptional;
}

[[nodiscard]] constexpr std::string_view FlowEnvelopeAttributeMissingReason(
    FlowEnvelopeAttribute attribute) {
  switch (attribute) {
    case FlowEnvelopeAttribute::kEventSequence: return "invalid_event_sequence";
    case FlowEnvelopeAttribute::kFlowId: return "invalid_flow_id";
    case FlowEnvelopeAttribute::kFlowSchema: return "invalid_flow_schema";
    case FlowEnvelopeAttribute::kPoint: return "point_name_mismatch";
    case FlowEnvelopeAttribute::kProducer: return "missing_producer";
    case FlowEnvelopeAttribute::kServiceInstance: return "missing_service_instance";
    case FlowEnvelopeAttribute::kServiceLogicalInstance: return "missing_service_logical_instance";
    case FlowEnvelopeAttribute::kCount: break;
  }
  return {};
}

using FlowAttributeMask = std::uint16_t;

enum class FlowAttribute : FlowAttributeMask {
  kAttempt = FlowAttributeMask{1} << 0,
  kJobId = FlowAttributeMask{1} << 1,
  kNodeId = FlowAttributeMask{1} << 2,
  kOperation = FlowAttributeMask{1} << 3,
  kOutcome = FlowAttributeMask{1} << 4,
  kReasonCode = FlowAttributeMask{1} << 5,
  kStatus = FlowAttributeMask{1} << 6,
  kStepId = FlowAttributeMask{1} << 7,
  kTaskId = FlowAttributeMask{1} << 8,
};

[[nodiscard]] constexpr std::string_view FlowAttributeName(
    FlowAttribute attribute) {
  switch (attribute) {
    case FlowAttribute::kAttempt: return "attempt";
    case FlowAttribute::kJobId: return "job_id";
    case FlowAttribute::kNodeId: return "node_id";
    case FlowAttribute::kOperation: return "operation";
    case FlowAttribute::kOutcome: return "outcome";
    case FlowAttribute::kReasonCode: return "reason_code";
    case FlowAttribute::kStatus: return "status";
    case FlowAttribute::kStepId: return "step_id";
    case FlowAttribute::kTaskId: return "task_id";
  }
  return {};
}

[[nodiscard]] constexpr FlowWireType FlowAttributeWireType(
    FlowAttribute attribute) {
  switch (attribute) {
    case FlowAttribute::kAttempt: return FlowWireType::kInt64;
    case FlowAttribute::kJobId: return FlowWireType::kInt64;
    case FlowAttribute::kNodeId: return FlowWireType::kString;
    case FlowAttribute::kOperation: return FlowWireType::kEnum;
    case FlowAttribute::kOutcome: return FlowWireType::kEnum;
    case FlowAttribute::kReasonCode: return FlowWireType::kEnum;
    case FlowAttribute::kStatus: return FlowWireType::kInt64;
    case FlowAttribute::kStepId: return FlowWireType::kInt64;
    case FlowAttribute::kTaskId: return FlowWireType::kInt64;
  }
  return FlowWireType::kString;
}

[[nodiscard]] constexpr FlowAttributeMask FlowAttributeBit(
    FlowAttribute attribute) {
  return static_cast<FlowAttributeMask>(attribute);
}

[[nodiscard]] constexpr bool FlowAttributesContain(
    FlowAttributeMask present, FlowAttributeMask required) {
  return (present & required) == required;
}

enum class FlowPoint {
  kCranedJobInstalled,
  kCranedJobRemoved,
  kCranedStatusSendResult,
  kCranedStepCleanupFinished,
  kCranedStepCleanupStarted,
  kCranedStepExecuteAccepted,
  kCranedStepFreeAccepted,
  kCranedStepInstallAccepted,
  kCranedStepInstalled,
  kCranedSupervisorExitObserved,
  kCranedSupervisorForked,
  kCranedSupervisorReady,
  kCtldJobAccepted,
  kCtldJobAllocRpcResult,
  kCtldJobAllocated,
  kCtldJobAllocationPersisted,
  kCtldJobEmbeddedPersisted,
  kCtldJobFreeResult,
  kCtldJobMongoPersisted,
  kCtldJobResourcesReleased,
  kCtldJobTerminal,
  kCtldJobUnsupported,
  kCtldStatusApplied,
  kCtldStatusReceived,
  kCtldStepAllCompleting,
  kCtldStepAllConfigured,
  kCtldStepAllTerminal,
  kCtldStepAllocRpcResult,
  kCtldStepExecuteRequested,
  kCtldStepExecuteRpcResult,
  kCtldStepFreeRpcResult,
  kPipelineFault,
  kSupervisorStepAllTasksFinalized,
  kSupervisorStepCompletingEnqueued,
  kSupervisorStepEpilogFinished,
  kSupervisorStepExecuteStarted,
  kSupervisorStepExiting,
  kSupervisorStepInitialized,
  kSupervisorStepShutdownReceived,
  kSupervisorTaskExitObserved,
  kSupervisorTaskFinalized,
  kSupervisorTaskPrepared,
  kSupervisorTaskSpawned,
  kCount,
};

[[nodiscard]] constexpr std::string_view FlowPointName(FlowPoint point) {
  switch (point) {
    case FlowPoint::kCranedJobInstalled: return "craned/job/installed";
    case FlowPoint::kCranedJobRemoved: return "craned/job/removed";
    case FlowPoint::kCranedStatusSendResult: return "craned/status/send_result";
    case FlowPoint::kCranedStepCleanupFinished: return "craned/step/cleanup_finished";
    case FlowPoint::kCranedStepCleanupStarted: return "craned/step/cleanup_started";
    case FlowPoint::kCranedStepExecuteAccepted: return "craned/step/execute_accepted";
    case FlowPoint::kCranedStepFreeAccepted: return "craned/step/free_accepted";
    case FlowPoint::kCranedStepInstallAccepted: return "craned/step/install_accepted";
    case FlowPoint::kCranedStepInstalled: return "craned/step/installed";
    case FlowPoint::kCranedSupervisorExitObserved: return "craned/supervisor/exit_observed";
    case FlowPoint::kCranedSupervisorForked: return "craned/supervisor/forked";
    case FlowPoint::kCranedSupervisorReady: return "craned/supervisor/ready";
    case FlowPoint::kCtldJobAccepted: return "ctld/job/accepted";
    case FlowPoint::kCtldJobAllocRpcResult: return "ctld/job/alloc_rpc_result";
    case FlowPoint::kCtldJobAllocated: return "ctld/job/allocated";
    case FlowPoint::kCtldJobAllocationPersisted: return "ctld/job/allocation_persisted";
    case FlowPoint::kCtldJobEmbeddedPersisted: return "ctld/job/embedded_persisted";
    case FlowPoint::kCtldJobFreeResult: return "ctld/job/free_result";
    case FlowPoint::kCtldJobMongoPersisted: return "ctld/job/mongo_persisted";
    case FlowPoint::kCtldJobResourcesReleased: return "ctld/job/resources_released";
    case FlowPoint::kCtldJobTerminal: return "ctld/job/terminal";
    case FlowPoint::kCtldJobUnsupported: return "ctld/job/unsupported";
    case FlowPoint::kCtldStatusApplied: return "ctld/status/applied";
    case FlowPoint::kCtldStatusReceived: return "ctld/status/received";
    case FlowPoint::kCtldStepAllCompleting: return "ctld/step/all_completing";
    case FlowPoint::kCtldStepAllConfigured: return "ctld/step/all_configured";
    case FlowPoint::kCtldStepAllTerminal: return "ctld/step/all_terminal";
    case FlowPoint::kCtldStepAllocRpcResult: return "ctld/step/alloc_rpc_result";
    case FlowPoint::kCtldStepExecuteRequested: return "ctld/step/execute_requested";
    case FlowPoint::kCtldStepExecuteRpcResult: return "ctld/step/execute_rpc_result";
    case FlowPoint::kCtldStepFreeRpcResult: return "ctld/step/free_rpc_result";
    case FlowPoint::kPipelineFault: return "pipeline/fault";
    case FlowPoint::kSupervisorStepAllTasksFinalized: return "supervisor/step/all_tasks_finalized";
    case FlowPoint::kSupervisorStepCompletingEnqueued: return "supervisor/step/completing_enqueued";
    case FlowPoint::kSupervisorStepEpilogFinished: return "supervisor/step/epilog_finished";
    case FlowPoint::kSupervisorStepExecuteStarted: return "supervisor/step/execute_started";
    case FlowPoint::kSupervisorStepExiting: return "supervisor/step/exiting";
    case FlowPoint::kSupervisorStepInitialized: return "supervisor/step/initialized";
    case FlowPoint::kSupervisorStepShutdownReceived: return "supervisor/step/shutdown_received";
    case FlowPoint::kSupervisorTaskExitObserved: return "supervisor/task/exit_observed";
    case FlowPoint::kSupervisorTaskFinalized: return "supervisor/task/finalized";
    case FlowPoint::kSupervisorTaskPrepared: return "supervisor/task/prepared";
    case FlowPoint::kSupervisorTaskSpawned: return "supervisor/task/spawned";
    case FlowPoint::kCount: break;
  }
  return {};
}

[[nodiscard]] constexpr std::string_view FlowPointProducer(FlowPoint point) {
  switch (point) {
    case FlowPoint::kCranedJobInstalled: return "craned";
    case FlowPoint::kCranedJobRemoved: return "craned";
    case FlowPoint::kCranedStatusSendResult: return "craned";
    case FlowPoint::kCranedStepCleanupFinished: return "craned";
    case FlowPoint::kCranedStepCleanupStarted: return "craned";
    case FlowPoint::kCranedStepExecuteAccepted: return "craned";
    case FlowPoint::kCranedStepFreeAccepted: return "craned";
    case FlowPoint::kCranedStepInstallAccepted: return "craned";
    case FlowPoint::kCranedStepInstalled: return "craned";
    case FlowPoint::kCranedSupervisorExitObserved: return "craned";
    case FlowPoint::kCranedSupervisorForked: return "craned";
    case FlowPoint::kCranedSupervisorReady: return "craned";
    case FlowPoint::kCtldJobAccepted: return "cranectld";
    case FlowPoint::kCtldJobAllocRpcResult: return "cranectld";
    case FlowPoint::kCtldJobAllocated: return "cranectld";
    case FlowPoint::kCtldJobAllocationPersisted: return "cranectld";
    case FlowPoint::kCtldJobEmbeddedPersisted: return "cranectld";
    case FlowPoint::kCtldJobFreeResult: return "cranectld";
    case FlowPoint::kCtldJobMongoPersisted: return "cranectld";
    case FlowPoint::kCtldJobResourcesReleased: return "cranectld";
    case FlowPoint::kCtldJobTerminal: return "cranectld";
    case FlowPoint::kCtldJobUnsupported: return "cranectld";
    case FlowPoint::kCtldStatusApplied: return "cranectld";
    case FlowPoint::kCtldStatusReceived: return "cranectld";
    case FlowPoint::kCtldStepAllCompleting: return "cranectld";
    case FlowPoint::kCtldStepAllConfigured: return "cranectld";
    case FlowPoint::kCtldStepAllTerminal: return "cranectld";
    case FlowPoint::kCtldStepAllocRpcResult: return "cranectld";
    case FlowPoint::kCtldStepExecuteRequested: return "cranectld";
    case FlowPoint::kCtldStepExecuteRpcResult: return "cranectld";
    case FlowPoint::kCtldStepFreeRpcResult: return "cranectld";
    case FlowPoint::kPipelineFault: return "frontend";
    case FlowPoint::kSupervisorStepAllTasksFinalized: return "supervisor";
    case FlowPoint::kSupervisorStepCompletingEnqueued: return "supervisor";
    case FlowPoint::kSupervisorStepEpilogFinished: return "supervisor";
    case FlowPoint::kSupervisorStepExecuteStarted: return "supervisor";
    case FlowPoint::kSupervisorStepExiting: return "supervisor";
    case FlowPoint::kSupervisorStepInitialized: return "supervisor";
    case FlowPoint::kSupervisorStepShutdownReceived: return "supervisor";
    case FlowPoint::kSupervisorTaskExitObserved: return "supervisor";
    case FlowPoint::kSupervisorTaskFinalized: return "supervisor";
    case FlowPoint::kSupervisorTaskPrepared: return "supervisor";
    case FlowPoint::kSupervisorTaskSpawned: return "supervisor";
    case FlowPoint::kCount: break;
  }
  return {};
}

[[nodiscard]] constexpr FlowAttributeMask FlowPointRequiredAttributes(
    FlowPoint point) {
  switch (point) {
    case FlowPoint::kCranedJobInstalled: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCranedJobRemoved: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCranedStatusSendResult: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCranedStepCleanupFinished: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCranedStepCleanupStarted: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation);
    case FlowPoint::kCranedStepExecuteAccepted: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCranedStepFreeAccepted: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCranedStepInstallAccepted: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCranedStepInstalled: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCranedSupervisorExitObserved: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCranedSupervisorForked: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCranedSupervisorReady: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldJobAccepted: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldJobAllocRpcResult: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldJobAllocated: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldJobAllocationPersisted: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldJobEmbeddedPersisted: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldJobFreeResult: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldJobMongoPersisted: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldJobResourcesReleased: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldJobTerminal: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldJobUnsupported: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome) | FlowAttributeBit(FlowAttribute::kReasonCode);
    case FlowPoint::kCtldStatusApplied: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldStatusReceived: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation);
    case FlowPoint::kCtldStepAllCompleting: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldStepAllConfigured: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldStepAllTerminal: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation);
    case FlowPoint::kCtldStepAllocRpcResult: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldStepExecuteRequested: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldStepExecuteRpcResult: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCtldStepFreeRpcResult: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kPipelineFault: return FlowAttributeBit(FlowAttribute::kReasonCode);
    case FlowPoint::kSupervisorStepAllTasksFinalized: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation);
    case FlowPoint::kSupervisorStepCompletingEnqueued: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kSupervisorStepEpilogFinished: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kSupervisorStepExecuteStarted: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kSupervisorStepExiting: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation);
    case FlowPoint::kSupervisorStepInitialized: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kSupervisorStepShutdownReceived: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation);
    case FlowPoint::kSupervisorTaskExitObserved: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kTaskId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kSupervisorTaskFinalized: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kTaskId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kStatus) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kSupervisorTaskPrepared: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kTaskId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kSupervisorTaskSpawned: return FlowAttributeBit(FlowAttribute::kJobId) | FlowAttributeBit(FlowAttribute::kStepId) | FlowAttributeBit(FlowAttribute::kTaskId) | FlowAttributeBit(FlowAttribute::kNodeId) | FlowAttributeBit(FlowAttribute::kOperation) | FlowAttributeBit(FlowAttribute::kOutcome);
    case FlowPoint::kCount: break;
  }
  return {};
}

[[nodiscard]] constexpr bool FlowPointRequires(FlowPoint point,
                                                FlowAttribute attribute) {
  return FlowAttributesContain(FlowPointRequiredAttributes(point),
                               FlowAttributeBit(attribute));
}

enum class FlowOperation {
  kAllocJobs,
  kAllocSteps,
  kAllocate,
  kCancelPendingJob,
  kDaemonCleanup,
  kDaemonConfigure,
  kDaemonTerminal,
  kEmbeddedDbCommit,
  kEmbeddedDbFinalize,
  kEnqueueStatus,
  kExecuteStep,
  kExecuteSteps,
  kExitSupervisor,
  kFinalizeStep,
  kFinalizeTask,
  kForkSupervisor,
  kFreeJobs,
  kFreeStep,
  kFreeSteps,
  kInitialize,
  kInitializeSupervisor,
  kInstallJob,
  kInstallStep,
  kJobCleanup,
  kJobTerminal,
  kMongodbFinalize,
  kObserveSupervisorExit,
  kObserveTaskExit,
  kPrepareTask,
  kReleaseResources,
  kRemoveJob,
  kRequeue,
  kSendStatusChange,
  kShutdownSupervisor,
  kSpawnTask,
  kStateMachine,
  kStatusChange,
  kStepCleanup,
  kStepConfigure,
  kStepTerminal,
  kSubmit,
  kSubmitCommonStep,
  kSupervisorEpilog,
};

[[nodiscard]] constexpr std::string_view FlowOperationName(FlowOperation value) {
  switch (value) {
    case FlowOperation::kAllocJobs: return "alloc-jobs";
    case FlowOperation::kAllocSteps: return "alloc-steps";
    case FlowOperation::kAllocate: return "allocate";
    case FlowOperation::kCancelPendingJob: return "cancel-pending-job";
    case FlowOperation::kDaemonCleanup: return "daemon-cleanup";
    case FlowOperation::kDaemonConfigure: return "daemon-configure";
    case FlowOperation::kDaemonTerminal: return "daemon-terminal";
    case FlowOperation::kEmbeddedDbCommit: return "embedded-db-commit";
    case FlowOperation::kEmbeddedDbFinalize: return "embedded-db-finalize";
    case FlowOperation::kEnqueueStatus: return "enqueue-status";
    case FlowOperation::kExecuteStep: return "execute-step";
    case FlowOperation::kExecuteSteps: return "execute-steps";
    case FlowOperation::kExitSupervisor: return "exit-supervisor";
    case FlowOperation::kFinalizeStep: return "finalize-step";
    case FlowOperation::kFinalizeTask: return "finalize-task";
    case FlowOperation::kForkSupervisor: return "fork-supervisor";
    case FlowOperation::kFreeJobs: return "free-jobs";
    case FlowOperation::kFreeStep: return "free-step";
    case FlowOperation::kFreeSteps: return "free-steps";
    case FlowOperation::kInitialize: return "initialize";
    case FlowOperation::kInitializeSupervisor: return "initialize-supervisor";
    case FlowOperation::kInstallJob: return "install-job";
    case FlowOperation::kInstallStep: return "install-step";
    case FlowOperation::kJobCleanup: return "job-cleanup";
    case FlowOperation::kJobTerminal: return "job-terminal";
    case FlowOperation::kMongodbFinalize: return "mongodb-finalize";
    case FlowOperation::kObserveSupervisorExit: return "observe-supervisor-exit";
    case FlowOperation::kObserveTaskExit: return "observe-task-exit";
    case FlowOperation::kPrepareTask: return "prepare-task";
    case FlowOperation::kReleaseResources: return "release-resources";
    case FlowOperation::kRemoveJob: return "remove-job";
    case FlowOperation::kRequeue: return "requeue";
    case FlowOperation::kSendStatusChange: return "send-status-change";
    case FlowOperation::kShutdownSupervisor: return "shutdown-supervisor";
    case FlowOperation::kSpawnTask: return "spawn-task";
    case FlowOperation::kStateMachine: return "state-machine";
    case FlowOperation::kStatusChange: return "status-change";
    case FlowOperation::kStepCleanup: return "step-cleanup";
    case FlowOperation::kStepConfigure: return "step-configure";
    case FlowOperation::kStepTerminal: return "step-terminal";
    case FlowOperation::kSubmit: return "submit";
    case FlowOperation::kSubmitCommonStep: return "submit-common-step";
    case FlowOperation::kSupervisorEpilog: return "supervisor-epilog";
  }
  return {};
}

enum class FlowOutcome {
  kAccepted,
  kApplied,
  kCleanupFailure,
  kCompleted,
  kCranedDown,
  kEarlyCancel,
  kExit,
  kExited,
  kFailure,
  kPersisted,
  kPreStartFailure,
  kQueued,
  kRejected,
  kRequested,
  kRpcFailure,
  kSignal,
  kSkipped,
  kStarted,
  kSuccess,
  kUnsupported,
};

[[nodiscard]] constexpr std::string_view FlowOutcomeName(FlowOutcome value) {
  switch (value) {
    case FlowOutcome::kAccepted: return "accepted";
    case FlowOutcome::kApplied: return "applied";
    case FlowOutcome::kCleanupFailure: return "cleanup-failure";
    case FlowOutcome::kCompleted: return "completed";
    case FlowOutcome::kCranedDown: return "craned-down";
    case FlowOutcome::kEarlyCancel: return "early-cancel";
    case FlowOutcome::kExit: return "exit";
    case FlowOutcome::kExited: return "exited";
    case FlowOutcome::kFailure: return "failure";
    case FlowOutcome::kPersisted: return "persisted";
    case FlowOutcome::kPreStartFailure: return "pre-start-failure";
    case FlowOutcome::kQueued: return "queued";
    case FlowOutcome::kRejected: return "rejected";
    case FlowOutcome::kRequested: return "requested";
    case FlowOutcome::kRpcFailure: return "rpc-failure";
    case FlowOutcome::kSignal: return "signal";
    case FlowOutcome::kSkipped: return "skipped";
    case FlowOutcome::kStarted: return "started";
    case FlowOutcome::kSuccess: return "success";
    case FlowOutcome::kUnsupported: return "unsupported";
  }
  return {};
}

enum class FlowReasonCode {
  kArrayJob,
  kCancelledBeforeAllocation,
  kContainerJob,
  kExtraCommonStep,
  kFlowEnvironmentIdMismatch,
  kInvalidAttributeType,
  kInvalidEnumValue,
  kInvalidEventSequence,
  kInvalidEventTime,
  kInvalidFlowId,
  kInvalidFlowSchema,
  kInvalidIntegerAttribute,
  kInvalidSpanId,
  kMissingFlowEnvironmentId,
  kMissingProducer,
  kMissingRequiredAttribute,
  kMissingServiceInstance,
  kMissingServiceLogicalInstance,
  kNonBatchJob,
  kPointNameMismatch,
  kProducerMismatch,
  kRequeueAttempt,
  kRequeueEnabled,
  kStorageCapacityExceeded,
  kUnexpectedAttribute,
  kUnknownPoint,
};

[[nodiscard]] constexpr std::string_view FlowReasonCodeName(FlowReasonCode value) {
  switch (value) {
    case FlowReasonCode::kArrayJob: return "array-job";
    case FlowReasonCode::kCancelledBeforeAllocation: return "cancelled-before-allocation";
    case FlowReasonCode::kContainerJob: return "container-job";
    case FlowReasonCode::kExtraCommonStep: return "extra-common-step";
    case FlowReasonCode::kFlowEnvironmentIdMismatch: return "flow_environment_id_mismatch";
    case FlowReasonCode::kInvalidAttributeType: return "invalid_attribute_type";
    case FlowReasonCode::kInvalidEnumValue: return "invalid_enum_value";
    case FlowReasonCode::kInvalidEventSequence: return "invalid_event_sequence";
    case FlowReasonCode::kInvalidEventTime: return "invalid_event_time";
    case FlowReasonCode::kInvalidFlowId: return "invalid_flow_id";
    case FlowReasonCode::kInvalidFlowSchema: return "invalid_flow_schema";
    case FlowReasonCode::kInvalidIntegerAttribute: return "invalid_integer_attribute";
    case FlowReasonCode::kInvalidSpanId: return "invalid_span_id";
    case FlowReasonCode::kMissingFlowEnvironmentId: return "missing_flow_environment_id";
    case FlowReasonCode::kMissingProducer: return "missing_producer";
    case FlowReasonCode::kMissingRequiredAttribute: return "missing_required_attribute";
    case FlowReasonCode::kMissingServiceInstance: return "missing_service_instance";
    case FlowReasonCode::kMissingServiceLogicalInstance: return "missing_service_logical_instance";
    case FlowReasonCode::kNonBatchJob: return "non-batch-job";
    case FlowReasonCode::kPointNameMismatch: return "point_name_mismatch";
    case FlowReasonCode::kProducerMismatch: return "producer_mismatch";
    case FlowReasonCode::kRequeueAttempt: return "requeue-attempt";
    case FlowReasonCode::kRequeueEnabled: return "requeue-enabled";
    case FlowReasonCode::kStorageCapacityExceeded: return "storage_capacity_exceeded";
    case FlowReasonCode::kUnexpectedAttribute: return "unexpected_attribute";
    case FlowReasonCode::kUnknownPoint: return "unknown_point";
  }
  return {};
}

// clang-format on

}  // namespace crane
