name: Build and Upload Artifacts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.cn-shanghai.aliyuncs.com/nativus/cranedev:ci

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure
        run: |
          mkdir -p out
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_UNQLITE=ON -DENABLE_BERKELEY_DB=OFF -DCRANE_FULL_DYNAMIC=OFF -DCRANE_USE_GITEE_SOURCE=OFF -S . -B out

      - name: Build
        run: |
          cmake --build out --config Release --target all

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ${{ github.workspace }}/out/src/Craned/craned
            ${{ github.workspace }}/out/src/CraneCtld/cranectld
            ${{ github.workspace }}/out/src/Misc/Pam/pam_crane.so
            ${{ github.workspace }}/etc/crane.conf
          retention-days: 30
          if-no-files-found: error
